// Login action types
export const CUSTOMER_LOGIN_REQUEST = "CUSTOMER_LOGIN_REQUEST";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAILURE = "CUSTOMER_LOGIN_FAILURE";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";


export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

// accounts action types
export const LOAD_ALL_ACCOUNTS_REQUEST = "LOAD_ALL_ACCOUNTS_REQUEST";
export const LOAD_ALL_ACCOUNTS_SUCCESS = "LOAD_ALL_ACCOUNTS_SUCCESS";
export const LOAD_ALL_ACCOUNTS_FAILURE = "LOAD_ALL_ACCOUNTS_FAILURE";

export const CREATE_ACCOUNT_START = "CREATE_ACCOUNT_START"
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS"
export const CREATE_ACCOUNT_ERROR = "CREATE_ACCOUNT_ERROR"

export const DELETE_ACCOUNT_REQUEST = "DELETE_ACCOUNT_REQUEST";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE = "DELETE_ACCOUNT_FAILURE";


// Load tranfers action types
export const LOAD_ALL_TRANSFER_REQUEST = "LOAD_ALL_TRANSFER_REQUEST";
export const LOAD_ALL_TRANSFER_SUCCESS = "LOAD_ALL_TRANSFER_SUCCESS";
export const LOAD_ALL_TRANSFER_FAILURE = "LOAD_ALL_TRANSFER_FAILURE";


export const LOAD_TRANSACTION_TRANSFER_REQUEST = "LOAD_TRANSACTION_TRANSFER_REQUEST";
export const LOAD_TRANSACTION_TRANSFER_SUCCESS = "LOAD_TRANSACTION_TRANSFER_SUCCESS";
export const LOAD_TRANSACTION_TRANSFER_FAILURE = "LOAD_TRANSACTION_TRANSFER_FAILURE";
